# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFactory < Formula
  desc "A factory code autogenator for Go."
  homepage "https://github.com/jotadrilo/go-factory"
  version "1.0.3"

  on_macos do
    on_intel do
      url "https://github.com/jotadrilo/go-factory/releases/download/1.0.3/go-factory_1.0.3_darwin_x86_64.tar.gz"
      sha256 "882b9faba49516124b14871981f336f6b2c8558bff1dc9417c90de89d8c1d47a"

      def install
        bin.install "go-factory"
      end
    end
    on_arm do
      url "https://github.com/jotadrilo/go-factory/releases/download/1.0.3/go-factory_1.0.3_darwin_arm64.tar.gz"
      sha256 "9c25a28fc74af51025021823d0bbc61059a7fe7e41a040ffd0f4d221736e087e"

      def install
        bin.install "go-factory"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jotadrilo/go-factory/releases/download/1.0.3/go-factory_1.0.3_linux_x86_64.tar.gz"
        sha256 "2fef0f9e3dafa069cfc82351f7ff20b337c2ad4ce60877e92e0a46f19170e28f"

        def install
          bin.install "go-factory"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jotadrilo/go-factory/releases/download/1.0.3/go-factory_1.0.3_linux_arm64.tar.gz"
        sha256 "a4440f0b733aa3e331a7fdf6610dc1e8f379551c5a709b4ab6fa48fb5e381503"

        def install
          bin.install "go-factory"
        end
      end
    end
  end

  test do
    system bin/"go-factory", "-version"
  end
end
