# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoFactory < Formula
  desc "A factory code autogenator for Go."
  homepage "https://github.com/jotadrilo/go-factory"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/jotadrilo/go-factory/releases/download/1.0.1/go-factory_1.0.1_darwin_x86_64.tar.gz"
      sha256 "d6b4f8947044117e83b0a6015c8b16304db646b97b1e0d593bed261523b7b40a"

      def install
        bin.install "go-factory"
      end
    end
    on_arm do
      url "https://github.com/jotadrilo/go-factory/releases/download/1.0.1/go-factory_1.0.1_darwin_arm64.tar.gz"
      sha256 "4016577ab5264d56a9cb10447b976d9024beb94143772f61c1b327c2b3322f40"

      def install
        bin.install "go-factory"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jotadrilo/go-factory/releases/download/1.0.1/go-factory_1.0.1_linux_x86_64.tar.gz"
        sha256 "eb3cc08caf4d1763952a632abccfd219ab8f09f30a97fe2f16c86c62baef0d77"

        def install
          bin.install "go-factory"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jotadrilo/go-factory/releases/download/1.0.1/go-factory_1.0.1_linux_arm64.tar.gz"
        sha256 "582cae3405e68154ba4e2ee54b6696148bc9ead2a001a19b404ee2e957ecc173"

        def install
          bin.install "go-factory"
        end
      end
    end
  end

  test do
    system bin/"go-factory", "-version"
  end
end
