# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubectxext < Formula
  desc "CLI to extract a context from an existing kubernetes configuration file"
  homepage "https://github.com/jotadrilo/kubectxext"
  version "1.0.0"

  on_macos do
    url "https://github.com/jotadrilo/kubectxext/releases/download/v1.0.0/kubectxext_1.0.0_darwin_x86_64.tar.gz"
    sha256 "2ddcfe3185ab94e7311efbe5fa01e04c46394e9c48e838255bde1b99bb5bcf17"

    def install
      bin.install "kubectxext"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kubectxext
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jotadrilo/kubectxext/releases/download/v1.0.0/kubectxext_1.0.0_linux_x86_64.tar.gz"
      sha256 "926e30a77860ddfe5c1d2c6891e54938d165a98b8f7b9e4bd0ded3e9e8a0065f"

      def install
        bin.install "kubectxext"
      end
    end
  end

  test do
    system bin/"kubectxext", "-help"
  end
end
