# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubectxext < Formula
  desc "CLI to extract a context from an existing kubernetes configuration file"
  homepage "https://github.com/jotadrilo/kubectxext"
  version "1.0.1"

  on_macos do
    url "https://github.com/jotadrilo/kubectxext/releases/download/v1.0.1/kubectxext_1.0.1_darwin_x86_64.tar.gz"
    sha256 "dbc4a5c6f3c73c468b7746673bbc5ce9ca5cb01437a03090a4ebb9e94dfb6be8"

    def install
      bin.install "kubectxext"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Kubectxext
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jotadrilo/kubectxext/releases/download/v1.0.1/kubectxext_1.0.1_linux_x86_64.tar.gz"
      sha256 "b5a2fa3322e627513255d89c64a2d74e3076fdba64eafa1644365884672200e9"

      def install
        bin.install "kubectxext"
      end
    end
  end

  test do
    system bin/"kubectxext", "-help"
  end
end
