# This file was generated by GoReleaser. DO NOT EDIT.
class RubbiSh < Formula
  desc "Go and Shell helpers to provide a sandbox directory for rubbish."
  homepage "https://github.com/jotadrilo/rubbi-sh"
  version "0.0.14"

  if OS.mac?
    url "https://github.com/jotadrilo/rubbi-sh/releases/download/0.0.14/rubbi-sh_0.0.14_darwin_x86_64.tar.gz"
    sha256 "58ea4a09b9aae3eec5bfb896f39699222acc00ac4e9db6b6c286d8a9e8a35e34"
  elsif OS.linux?
    url "https://github.com/jotadrilo/rubbi-sh/releases/download/0.0.14/rubbi-sh_0.0.14_linux_x86_64.tar.gz"
    sha256 "9fe1835c239dcb789c6150acd9dd63b3f3790debca971152e58978cae5745344"
  end

  def install
    bin.install "rubbi-sh"
    (share/"alias").install "dotfiles/.rubbi.sh"
    (share/"alias").install "dotfiles/.rubbi.minimal.sh"
  end

  def caveats; <<~EOS
    Please import the .rubbi.sh file in your profile configuration or add its content directly
    
     . #{(share/"alias")}/.rubbi.sh
    
    or the .rubbi.minimal.sh for a minimal setup (rbsh shell function only)
    
     . #{(share/"alias")}/.rubbi.minimal.sh
    
    This tool is based on some alias and shell functions that are core to work.
  EOS
  end

  test do
    system bin/"rubbi-sh", "-version"
  end
end
