# This file was generated by GoReleaser. DO NOT EDIT.
class RubbiSh < Formula
  desc "Go and Shell helpers to provide a sandbox directory for rubbish."
  homepage "https://github.com/jotadrilo/rubbi-sh"
  version "0.0.8"

  if OS.mac?
    url "https://github.com/jotadrilo/rubbi-sh/releases/download/0.0.8/rubbi-sh_0.0.8_darwin_x86_64.tar.gz"
    sha256 "0867f2a955a84eb7550296d5262aa8ff01ddfc041c0f8cf96748c194d4c4792a"
  elsif OS.linux?
    url "https://github.com/jotadrilo/rubbi-sh/releases/download/0.0.8/rubbi-sh_0.0.8_linux_x86_64.tar.gz"
    sha256 "411290aed0e2ac245b0ba4f343b38282e069d14cbc43470c5b9a5fb09ebdb362"
  end

  def install
    bin.install "rubbi-sh"
    (share/"alias").install "dotfiles/.rubbi.sh"
  end

  def caveats; <<~EOS
    Please import the .rubbi.sh file in your profile configuration or add its content directly
    
     . \#{(share/"alias")}/.rubbi.sh
    
    This tool is based on some alias and shell functions and they are core to work.
  EOS
  end

  test do
    system bin/"rubbi-sh", "-version"
  end
end
